[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.13.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[dev]
command    = "zola serve"
targetPort = 1111
framework  = "#custom"


[[redirects]]
from   = "https://braun-embedded.netlify.com/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://braun-robotics.com/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-robotics.com/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true
