[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.11.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"


# Page redirects

[[redirects]]
from   = "/custom-firmware-development"
to     = "/"
status = 301
force  = true

[[redirects]]
from   = "/services/custom-firmware-development"
to     = "/"
status = 301
force  = true


# Domain redirects

[[redirects]]
from   = "https://braun-embedded.netlify.com/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://braun-embedded.eu/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-embedded.eu/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://braun-robotics.com/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-robotics.com/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://braun-robotics.de/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-robotics.de/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://braun-robotics.eu/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true

[[redirects]]
from   = "https://www.braun-robotics.eu/*"
to     = "https://braun-embedded.com/:splat"
status = 301
force  = true
