[package]
name    = "example-rtic-type-state-init"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-odw.eu>"]
edition = "2018"


[dependencies]
cortex-m-rtic = "0.5.6"
panic-halt    = "0.2.0"

[dependencies.lpc8xx-hal]
version  = "0.9.0"
features = ["845-rt"]
